# Generated by Django 5.1.7 on 2025-03-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
