# Generated by Django 5.1.7 on 2025-03-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_workspace_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='people',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
